export {default as Splash} from './SplashScreen/SplashScreen';
export {default as Login} from './LoginScreen/LoginScreen';
export {default as Onboarding} from './OnBoardingScreen/OnBoardingScreen';
export {default as Home} from './Home/HomeScreen';
export {default as ResetPassword} from './ResetPasswordScreen/ResetPasswordScreen';
export {default as SignInScreen} from './SingInScreen/SignInScreen';
export {default as HomeClient} from './Client/Home/HomeScreen';
export {default as PetFormScreen} from './Client/PetFormScreen/PetFormScreen';
export {default as Mypet} from './Pets/Mypet';
